#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Revonia\BlogHub\Application;
use Revonia\BlogHub\Env;
use Revonia\BlogHub\Hub;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Reference;
use Symfony\Component\Dotenv\Dotenv;

$container = new ContainerBuilder();

$container->setAlias(ContainerBuilder::class, 'service_container')
    ->setPublic(true);

$container->autowire(Dotenv::class, Dotenv::class)->setPublic(false);
$container->autowire(Hub::class, Hub::class)->setPublic(true);
$container->autowire(Env::class, Env::class)->setPublic(true)->setShared(false);

$container->autowire(Application::class, Application::class)
    ->addArgument($container)
    ->addArgument(new Reference(Dotenv::class))
    ->addArgument(new Reference(Hub::class))
    ->addArgument(new Reference(Env::class))
    ->addMethodCall('setWorkingDir', [getcwd()]);


$container->get(Application::class)->run();
