#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Revonia\BlogHub\Application;
use Revonia\BlogHub\Hub;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Reference;
use Symfony\Component\Dotenv\Dotenv;

$container = new ContainerBuilder();

$container->autowire(Dotenv::class, Dotenv::class);
$container->autowire(Hub::class, Hub::class);

$container->register(Application::class, Application::class)
    ->addArgument(getcwd())
    ->addArgument($container)
    ->addArgument(new Reference(Dotenv::class))
    ->addArgument(new Reference(Hub::class))
    ->setAutowired(true);

$container->get(Application::class)->run();
